# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auzGc_7VVDntMUHdhZO69RFyvl97EzcD
"""

import numpy as np
import matplotlib.pyplot as plt

def calcular_errores(x, y, valor_real):
    diferencia = x - y
    error_abs = abs(valor_real - diferencia)
    error_rel = error_abs / abs(valor_real)
    error_pct = error_rel * 100
    return diferencia, error_abs, error_rel, error_pct

valores = [(1.0000001, 1.0000000, 0.0000001), (1.000000000000001, 1.000000000000000, 0.000000000000001)]

diferencias = []
errores_abs = []
errores_rel = []
errores_pct = []
labels = []

for i, (x, y, real) in enumerate(valores):
    diferencia, error_abs, error_rel, error_pct = calcular_errores(x, y, real)
    diferencias.append(diferencia)
    errores_abs.append(error_abs)
    errores_rel.append(error_rel)
    errores_pct.append(error_pct)
    labels.append(f"Caso {i+1}")

# Graficar los errores
x = np.arange(len(valores))
width = 0.2

fig, ax = plt.subplots(figsize=(10, 6))
ax.bar(x - 1.5*width, diferencias, width, label="Diferencia", color='blue')
ax.bar(x - 0.5*width, errores_abs, width, label="Error Absoluto", color='red')
ax.bar(x + 0.5*width, errores_rel, width, label="Error Relativo", color='green')
ax.bar(x + 1.5*width, errores_pct, width, label="Error Porcentual", color='orange')

ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_xlabel("Casos")
ax.set_ylabel("Errores")
ax.set_title("Comparación de Errores")
ax.legend()

plt.show()