# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVkHkBt6TlDyC7-XiNqr5q5U2djkC12u
"""

import numpy as np
import matplotlib.pyplot as plt

# Inicialización de variables
epsilon = 1.0
iteracion = 0
iteraciones = []
valores_epsilon = []

# Bucle para calcular la precisión de máquina
while 1.0 + epsilon != 1.0:
    iteraciones.append(iteracion)
    valores_epsilon.append(epsilon)
    epsilon /= 2
    iteracion += 1

# Ajuste del último valor
epsilon *= 2
iteraciones.append(iteracion)
valores_epsilon.append(epsilon)

# Graficar los valores de epsilon por iteración
plt.figure(figsize=(10, 5))
plt.bar(iteraciones, valores_epsilon, color='blue')
plt.yscale("log")  # Escala logarítmica para visualizar mejor
plt.xlabel("Iteración")
plt.ylabel("Valor de Épsilon")
plt.title("Precisión de Máquina en IEEE 754")
plt.show()